# .github/workflows/format.yml
name: Format Code
on: [push]

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'

            - name: Install dependencies
              run: npm ci

            - name: Format code
              run: npx prettier@latest --write .

            - name: Commit changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git diff --quiet && git diff --staged --quiet || (git add . && git commit -m "Format code")
