name: Format Code
on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm ci

    - name: Format code and stage changes
      run: |
        npx prettier@latest --write .
        git diff --name-only --diff-filter=d origin/main | while read file; do
          git diff --quiet "$file" || git add "$file"
        done

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --staged --quiet || git commit -m "Format code"